### PR TITLE
update to allow more danger in react :fireworks:

### PR DESCRIPTION
**Pull request by jks8787**

### CODE REVIEW

**Comment by kelvinma** [comment]
What's the context for this? The failing test?

**Comment by jks8787** [comment]
@kelvinma  yes that is what it for - that is why i connected them - sorry for the confusion

**Comment by zcotter** [comment]
@jks8787 @kelvinma @phereford 
I know we talked about this yesterday, but didn't think about XSS vulnerabilities.
I totally agree that the usage of dangerouslySetInnerHTML is totally safe in your other pull because those columns couldn't possibly contain malicious scripts.

But the usage of dangerouslySetInnerHTML is still dangerous in other scenarios.
So I think we should leave the rule on and add one off ignores ie `// eslint-disable-line react/no-danger` along with an explanation of why it is safe in each one-off scenario.

To review, in other future scenarios in which we used dangerouslySetInnerHTML to render longer user generated content (ie text field content), a user could enter javascript code that steals data from pages that only other user's can see on which the content is dangerously rendered

**Comment by jks8787** [comment]
closing after discussion

**Pull request closed without merging**
